server:
  port: 8082

spring:
  application:
    name: campaign-service
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: 6379
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: 5672
    username: admin
    password: admin
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
  datasource:
    url: ${DATASOURCE_URL}
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migrations
