apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgres.name }}-init
  namespace: {{ .Values.namespace }}
data:
  init-databases.sql: |
    CREATE DATABASE {{ .Values.services.sso.database }};
    CREATE DATABASE {{ .Values.services.campaign.database }};
    CREATE DATABASE {{ .Values.services.transaction.database }};
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  ports:
    - name: postgres
      port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
  selector:
    app: {{ .Values.postgres.name }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ .Values.postgres.name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgres.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.name }}
    spec:
      containers:
        - name: {{ .Values.postgres.name }}
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: launchpad-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: launchpad-secrets
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: {{ .Values.postgres.port }}
              name: postgres
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: {{ .Values.postgres.name }}-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: {{ .Values.postgres.name }}-init
          configMap:
            name: {{ .Values.postgres.name }}-init
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: {{ .Values.postgres.storage }}