server:
  port: 8081

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - Authentication
      routes:
        - id: sso-route
          uri: lb://sso-service
          predicates:
            - Path=/auth/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka