server:
  port: 8081

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}

spring:
  application:
    name: gateway-service
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: 6379
  cloud:
    gateway:
      default-filters:
        - Authentication
      routes:
        - id: sso-route
          uri: http://sso-service:8080
          predicates:
            - name: Path
              args:
                pattern: "/auth/**"
        - id: campaign-route
          uri: http://campaign-service:8082
          predicates:
            - name: Path
              args:
                pattern: "/campaigns/**"
        - id: transaction-route
          uri: http://transaction-service:8083
          predicates:
            - name: Path
              args:
                pattern: "/transactions/**"