server:
  port: 8081

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}

spring:
  application:
    name: gateway-service
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      default-filters:
        - Authentication
      routes:
        - id: sso-route
          uri: lb://sso-service
          predicates:
            - Path=/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 3
                redis-rate-limiter.burstCapacity: 3
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@userIpKeyResolver}"
        - id: campaign-route
          uri: lb://campaign-service
          predicates:
            - Path=/campaigns/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka