apiVersion: apps/v1
kind: Deployment
metadata:
  name: campaign-service
  namespace: token-launchpad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: campaign-service
  template:
    metadata:
      labels:
        app: campaign-service
    spec:
      containers:
        - name: campaign-service
          image: token-launchpad/campaign-service:local_v3
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
              name: http
          env:
            - name: DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/launchpad_campaign
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: launchpad-secrets
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: launchpad-secrets
                  key: POSTGRES_PASSWORD
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: launchpad-config
                  key: REDIS_HOST
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: launchpad-config
                  key: RABBITMQ_HOST
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: launchpad-secrets
                  key: RABBITMQ_USERNAME
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: launchpad-secrets
                  key: RABBITMQ_PASSWORD
          startupProbe:
            tcpSocket:
              port: http
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            tcpSocket:
              port: http
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: http
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: campaign-service
  namespace: token-launchpad
spec:
  type: ClusterIP
  selector:
    app: campaign-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
