CREATE TABLE campaigns
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time    TIMESTAMP(6),
    status        VARCHAR(255) NOT NULL,
    target_amount NUMERIC(38, 2),
    token_name    VARCHAR(255),
    tokens_sold   NUMERIC(38, 2)
);

CREATE TABLE campaign_reservations
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount         NUMERIC(38, 2),
    campaign_id    BIGINT,
    created_at     TIMESTAMP(6),
    failure_reason VARCHAR(255),
    status         VARCHAR(255) NOT NULL,
    transaction_id BIGINT NOT NULL,
    updated_at     TIMESTAMP(6),
    CONSTRAINT uk_transaction_id UNIQUE (transaction_id)
);

CREATE TABLE outbox_events
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id        BIGINT,
    created_at          TIMESTAMP(6),
    event_type          VARCHAR(255) NOT NULL,
    last_error          VARCHAR(255),
    next_attempt_at     TIMESTAMP(6),
    payload             TEXT,
    retry_count         INTEGER NOT NULL DEFAULT 0,
    set_next_attempt_at TIMESTAMP(6),
    status              VARCHAR(255) NOT NULL
);