FROM maven:3.9.9-eclipse-temurin-21 AS build

WORKDIR /workspace

COPY pom.xml .
COPY campaign-service/pom.xml campaign-service/pom.xml
COPY launchpad-common/pom.xml launchpad-common/pom.xml
COPY gateway-service/pom.xml gateway-service/pom.xml
COPY sso-service/pom.xml sso-service/pom.xml
COPY transaction-service/pom.xml transaction-service/pom.xml
COPY e2e-tests/pom.xml e2e-tests/pom.xml

RUN mvn -DskipTests -pl gateway-service -am dependency:go-offline

COPY launchpad-common/src launchpad-common/src
COPY gateway-service/src gateway-service/src

RUN mvn -DskipTests -pl gateway-service -am package

FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

COPY --from=build /workspace/gateway-service/target/gateway-service-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8081

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
