spring:
  application:
    name: sso-service
  datasource:
    url: ${DATASOURCE_URL}
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 3600000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
