server:
  port: 8080

spring:
  application:
    name: sso-service
  datasource:
    url: ${DATASOURCE_URL}
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migrations

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 3600000
